PS1="[\d \t] \u@\h\n\w\$ "
alias ls="ls -Gl"
alias vi="vim"
export cube="/Users/darren/cube/ds-front-app/src/business/cube"
export smart="/Users/darren/cube/ds-front-app/src/business/cube/js/app2/smart"
